from typing import ClassVar


class Colors:
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    BOLD = "\033[1m"
    ENDC = "\033[0m"
    DIM = "\033[90m"
    WHITE = "\033[37m"
    BG_RED = "\033[41m"


class Lang:
    tr: ClassVar[dict] = {
        "welcome": "=== LocalModeration for Matrix ===",
        "login": "[*] Giriş yapılıyor...",
        "login_fail": "[!] Giriş başarısız: ",
        "sync": "[*] Senkronizasyon...",
        "scan_start": "[*] Tarama Başlıyor",
        "scan_mode": "Mod: Public (Şifresiz)",
        "date_filter": "Tarih Filtresi: ",
        "scan_progress": "   > Tarandı: {} mesaj",
        "scan_done": "   -> Tarama tamamlandı. Toplam: {} mesaj.",
        "no_match": "[~] Kayıt bulunamadı.",
        "found_count": "[!] {} kayıt bulundu.",
        "review": "[ {} / {} ]",
        "action_prompt": ">> Sil? (y/N/a/q): ",
        "action_delete": "   -> Siliniyor...",
        "action_success": "   -> Silindi.",
        "action_fail": "   -> Hata: ",
        "action_all": "   -> Toplu silme başladı...",
        "action_exit": "İnceleme iptal edildi.",
        "prompt_user": "User ID (oturumları sıfırlamak için 'reset'): ",
        "prompt_pass": "Password: ",
        "quote_label": "[ALINTI]",
        "encrypted": "[Şifreli Mesaj]",
        "session_found": "[*] Kayıtlı oturum bulundu.",
        "session_saved": "[*] Oturum kaydedildi.",
        "log_push": "[*] Log odasına iletildi.",
        "media_mode": "[*] Medya Temizleme Modu.",
        "sticker_mode": "[*] Sticker Temizleme Modu.",
        "media_type": "Tür: {}",
        "warn_encrypted": "[!] {} şifreli mesaj atlandı.",
        "bulk_deleting": "Siliniyor: {} / {}",
        "bulk_failed": "Hata: {}",
        "bulk_eta": "ETA: {}",
        "interactive_title": "[*] İNTERAKTİF MOD",
        "interactive_user": " 1  Kullanıcı incele",
        "interactive_word": " 2  Kelime ara",
        "interactive_file": " 3  Wordlist dosyası ara",
        "interactive_media": " 4  Toplu medya sil (Önbellekten)",
        "interactive_sticker": " 5  Toplu sticker sil (Önbellekten)",
        "interactive_exit": " q  Çıkış",
        "interactive_prompt": "> ",
        "interactive_user_prompt": "Kullanıcı ID: ",
        "interactive_word_prompt": "Kelime: ",
        "interactive_file_prompt": "Dosya yolu: ",
        "file_not_found": "[!] Dosya bulunamadı.",
        "file_empty": "[!] Dosya boş veya okunamadı.",
        "cache_loaded": "[*] {} mesaj önbelleğe alındı.",
        "reset_confirm": "[!] Oturum dosyalarını silmek istediğinize emin misiniz? (y/N): ",
        "reset_done": "[*] Oturum başarıyla sıfırlandı. Lütfen programı tekrar çalıştırın.",
        "reset_cancel": "İşlem iptal edildi.",
        "scan_error": "[!] Sunucu hata döndürdü veya odaya erişilemiyor: {}",
        "scan_retry": "[!] Bağlantı hatası, bekleniyor... ({}/{})",
    }
    en: ClassVar[dict] = {
        "welcome": "=== LocalModeration for Matrix ===",
        "login": "[*] Logging in...",
        "login_fail": "[!] Login failed: ",
        "sync": "[*] Synchronizing...",
        "scan_start": "[*] Scanning Started",
        "scan_mode": "Mode: Public (Unencrypted)",
        "date_filter": "Date Filter: ",
        "scan_progress": "   > Scanned: {} msgs",
        "scan_done": "   -> Scan complete. Total: {} msgs.",
        "no_match": "[~] No records found.",
        "found_count": "[!] {} records found.",
        "review": "[ {} / {} ]",
        "action_prompt": ">> Delete? (y/N/a/q): ",
        "action_delete": "   -> Deleting...",
        "action_success": "   -> Deleted.",
        "action_fail": "   -> Error: ",
        "action_all": "   -> Bulk delete started...",
        "action_exit": "Review cancelled.",
        "prompt_user": "User ID (or 'reset' to clear session): ",
        "prompt_pass": "Password: ",
        "quote_label": "[QUOTE]",
        "encrypted": "[Encrypted Message]",
        "session_found": "[*] Saved session found.",
        "session_saved": "[*] Session saved.",
        "log_push": "[*] Logged to room.",
        "media_mode": "[*] Media Purge Mode.",
        "sticker_mode": "[*] Sticker Purge Mode.",
        "media_type": "Type: {}",
        "warn_encrypted": "[!] {} encrypted messages skipped.",
        "bulk_deleting": "Deleting: {} / {}",
        "bulk_failed": "Failed: {}",
        "bulk_eta": "ETA: {}",
        "interactive_title": "[*] INTERACTIVE MODE",
        "interactive_user": " 1  Review User",
        "interactive_word": " 2  Search Keyword",
        "interactive_file": " 3  Search File (Wordlist)",
        "interactive_media": " 4  Mass Media Purge (Cache)",
        "interactive_sticker": " 5  Mass Sticker Purge (Cache)",
        "interactive_exit": " q  Exit",
        "interactive_prompt": "> ",
        "interactive_user_prompt": "User ID: ",
        "interactive_word_prompt": "Keyword: ",
        "interactive_file_prompt": "File path: ",
        "file_not_found": "[!] File not found.",
        "file_empty": "[!] File is empty or unreadable.",
        "cache_loaded": "[*] {} messages cached.",
        "reset_confirm": "[!] Are you sure you want to delete session files? (y/N): ",
        "reset_done": "[*] Session reset successfully. Please run the program again.",
        "reset_cancel": "Operation cancelled.",
        "scan_error": "[!] Server returned an error or room is inaccessible: {}",
        "scan_retry": "[!] Connection error, waiting... ({}/{})",
    }
    de: ClassVar[dict] = {
        "welcome": "=== LocalModeration for Matrix ===",
        "login": "[*] Anmelden...",
        "login_fail": "[!] Anmeldung fehlgeschlagen: ",
        "sync": "[*] Synchronisierung...",
        "scan_start": "[*] Scan gestartet",
        "scan_mode": "Modus: Öffentlich (Unverschlüsselt)",
        "date_filter": "Datumsfilter: ",
        "scan_progress": "   > Gescannt: {} Nachr.",
        "scan_done": "   -> Scan abgeschlossen. Gesamt: {} Nachr.",
        "no_match": "[~] Keine Einträge gefunden.",
        "found_count": "[!] {} Einträge gefunden.",
        "review": "[ {} / {} ]",
        "action_prompt": ">> Löschen? (y/N/a/q): ",
        "action_delete": "   -> Wird gelöscht...",
        "action_success": "   -> Gelöscht.",
        "action_fail": "   -> Fehler: ",
        "action_all": "   -> Massenlöschung gestartet...",
        "action_exit": "Überprüfung abgebrochen.",
        "prompt_user": "Benutzer-ID ('reset' zum Zurücksetzen der Sitzung): ",
        "prompt_pass": "Passwort: ",
        "quote_label": "[ZITAT]",
        "encrypted": "[Verschlüsselte Nachricht]",
        "session_found": "[*] Gespeicherte Sitzung gefunden.",
        "session_saved": "[*] Sitzung gespeichert.",
        "log_push": "[*] Im Raum protokolliert.",
        "media_mode": "[*] Medien-Bereinigungsmodus.",
        "sticker_mode": "[*] Sticker-Bereinigungsmodus.",
        "media_type": "Typ: {}",
        "warn_encrypted": "[!] {} verschlüsselte Nachrichten übersprungen.",
        "bulk_deleting": "Lösche: {} / {}",
        "bulk_failed": "Fehler: {}",
        "bulk_eta": "ETA: {}",
        "interactive_title": "[*] INTERAKTIVER MODUS",
        "interactive_user": " 1  Benutzer überprüfen",
        "interactive_word": " 2  Schlüsselwort suchen",
        "interactive_file": " 3  Datei suchen (Wordlist)",
        "interactive_media": " 4  Massenmedien löschen (Cache)",
        "interactive_sticker": " 5  Massensticker löschen (Cache)",
        "interactive_exit": " q  Beenden",
        "interactive_prompt": "> ",
        "interactive_user_prompt": "Benutzer-ID: ",
        "interactive_word_prompt": "Schlüsselwort: ",
        "interactive_file_prompt": "Dateipfad: ",
        "file_not_found": "[!] Datei nicht gefunden.",
        "file_empty": "[!] Datei ist leer oder nicht lesbar.",
        "cache_loaded": "[*] {} Nachrichten zwischengespeichert.",
        "reset_confirm": "[!] Sind Sie sicher, dass Sie die Sitzungsdateien löschen möchten? (y/N): ",
        "reset_done": "[*] Sitzung erfolgreich zurückgesetzt. Bitte starten Sie das Programm erneut.",
        "reset_cancel": "Vorgang abgebrochen.",
        "scan_error": "[!] Server hat einen Fehler zurückgegeben oder Raum ist unzugänglich: {}",
        "scan_retry": "[!] Verbindungsfehler, warten... ({}/{})",
    }

    @staticmethod
    def get(lang_code: str) -> dict:
        if lang_code == "3" or lang_code == "tr":
            return Lang.tr
        elif lang_code == "2" or lang_code == "de":
            return Lang.de
        return Lang.en
